/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedZeitIndexRouteImport } from './routes/_authenticated/zeit/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedZeitAbrechnungRouteImport } from './routes/_authenticated/zeit/abrechnung'
import { Route as AuthenticatedAdminZeitUebersichtRouteImport } from './routes/_authenticated/admin/zeit-uebersicht'
import { Route as AuthenticatedAdminZeitRouteImport } from './routes/_authenticated/admin/zeit'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminMigrationRouteImport } from './routes/_authenticated/admin/migration'
import { Route as AuthenticatedAdminLocationsRouteImport } from './routes/_authenticated/admin/locations'
import { Route as AuthenticatedAdminKasseSaldoRouteImport } from './routes/_authenticated/admin/kasse-saldo'
import { Route as AuthenticatedAdminKasseRouteImport } from './routes/_authenticated/admin/kasse'
import { Route as AuthenticatedAdminImportZuordnungenRouteImport } from './routes/_authenticated/admin/import-zuordnungen'
import { Route as AuthenticatedAdminDienstplanRouteImport } from './routes/_authenticated/admin/dienstplan'
import { Route as AuthenticatedAdminStaffIndexRouteImport } from './routes/_authenticated/admin/staff.index'
import { Route as AuthenticatedAdminStaffNewRouteImport } from './routes/_authenticated/admin/staff.new'
import { Route as AuthenticatedAdminStaffStaffIdRouteImport } from './routes/_authenticated/admin/staff.$staffId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZeitIndexRoute = AuthenticatedZeitIndexRouteImport.update({
  id: '/zeit/',
  path: '/zeit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedZeitAbrechnungRoute =
  AuthenticatedZeitAbrechnungRouteImport.update({
    id: '/zeit/abrechnung',
    path: '/zeit/abrechnung',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminZeitUebersichtRoute =
  AuthenticatedAdminZeitUebersichtRouteImport.update({
    id: '/zeit-uebersicht',
    path: '/zeit-uebersicht',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminZeitRoute = AuthenticatedAdminZeitRouteImport.update({
  id: '/zeit',
  path: '/zeit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMigrationRoute =
  AuthenticatedAdminMigrationRouteImport.update({
    id: '/migration',
    path: '/migration',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLocationsRoute =
  AuthenticatedAdminLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKasseSaldoRoute =
  AuthenticatedAdminKasseSaldoRouteImport.update({
    id: '/kasse-saldo',
    path: '/kasse-saldo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKasseRoute = AuthenticatedAdminKasseRouteImport.update({
  id: '/kasse',
  path: '/kasse',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminImportZuordnungenRoute =
  AuthenticatedAdminImportZuordnungenRouteImport.update({
    id: '/import-zuordnungen',
    path: '/import-zuordnungen',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDienstplanRoute =
  AuthenticatedAdminDienstplanRouteImport.update({
    id: '/dienstplan',
    path: '/dienstplan',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStaffIndexRoute =
  AuthenticatedAdminStaffIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminStaffRoute,
  } as any)
const AuthenticatedAdminStaffNewRoute =
  AuthenticatedAdminStaffNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminStaffRoute,
  } as any)
const AuthenticatedAdminStaffStaffIdRoute =
  AuthenticatedAdminStaffStaffIdRouteImport.update({
    id: '/$staffId',
    path: '/$staffId',
    getParentRoute: () => AuthenticatedAdminStaffRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/dienstplan': typeof AuthenticatedAdminDienstplanRoute
  '/admin/import-zuordnungen': typeof AuthenticatedAdminImportZuordnungenRoute
  '/admin/kasse': typeof AuthenticatedAdminKasseRoute
  '/admin/kasse-saldo': typeof AuthenticatedAdminKasseSaldoRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/migration': typeof AuthenticatedAdminMigrationRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRouteWithChildren
  '/admin/zeit': typeof AuthenticatedAdminZeitRoute
  '/admin/zeit-uebersicht': typeof AuthenticatedAdminZeitUebersichtRoute
  '/zeit/abrechnung': typeof AuthenticatedZeitAbrechnungRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/zeit/': typeof AuthenticatedZeitIndexRoute
  '/admin/staff/$staffId': typeof AuthenticatedAdminStaffStaffIdRoute
  '/admin/staff/new': typeof AuthenticatedAdminStaffNewRoute
  '/admin/staff/': typeof AuthenticatedAdminStaffIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/dienstplan': typeof AuthenticatedAdminDienstplanRoute
  '/admin/import-zuordnungen': typeof AuthenticatedAdminImportZuordnungenRoute
  '/admin/kasse': typeof AuthenticatedAdminKasseRoute
  '/admin/kasse-saldo': typeof AuthenticatedAdminKasseSaldoRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/migration': typeof AuthenticatedAdminMigrationRoute
  '/admin/zeit': typeof AuthenticatedAdminZeitRoute
  '/admin/zeit-uebersicht': typeof AuthenticatedAdminZeitUebersichtRoute
  '/zeit/abrechnung': typeof AuthenticatedZeitAbrechnungRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/zeit': typeof AuthenticatedZeitIndexRoute
  '/admin/staff/$staffId': typeof AuthenticatedAdminStaffStaffIdRoute
  '/admin/staff/new': typeof AuthenticatedAdminStaffNewRoute
  '/admin/staff': typeof AuthenticatedAdminStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/dienstplan': typeof AuthenticatedAdminDienstplanRoute
  '/_authenticated/admin/import-zuordnungen': typeof AuthenticatedAdminImportZuordnungenRoute
  '/_authenticated/admin/kasse': typeof AuthenticatedAdminKasseRoute
  '/_authenticated/admin/kasse-saldo': typeof AuthenticatedAdminKasseSaldoRoute
  '/_authenticated/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/_authenticated/admin/migration': typeof AuthenticatedAdminMigrationRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRouteWithChildren
  '/_authenticated/admin/zeit': typeof AuthenticatedAdminZeitRoute
  '/_authenticated/admin/zeit-uebersicht': typeof AuthenticatedAdminZeitUebersichtRoute
  '/_authenticated/zeit/abrechnung': typeof AuthenticatedZeitAbrechnungRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/zeit/': typeof AuthenticatedZeitIndexRoute
  '/_authenticated/admin/staff/$staffId': typeof AuthenticatedAdminStaffStaffIdRoute
  '/_authenticated/admin/staff/new': typeof AuthenticatedAdminStaffNewRoute
  '/_authenticated/admin/staff/': typeof AuthenticatedAdminStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/dienstplan'
    | '/admin/import-zuordnungen'
    | '/admin/kasse'
    | '/admin/kasse-saldo'
    | '/admin/locations'
    | '/admin/migration'
    | '/admin/staff'
    | '/admin/zeit'
    | '/admin/zeit-uebersicht'
    | '/zeit/abrechnung'
    | '/admin/'
    | '/zeit/'
    | '/admin/staff/$staffId'
    | '/admin/staff/new'
    | '/admin/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/admin/dienstplan'
    | '/admin/import-zuordnungen'
    | '/admin/kasse'
    | '/admin/kasse-saldo'
    | '/admin/locations'
    | '/admin/migration'
    | '/admin/zeit'
    | '/admin/zeit-uebersicht'
    | '/zeit/abrechnung'
    | '/admin'
    | '/zeit'
    | '/admin/staff/$staffId'
    | '/admin/staff/new'
    | '/admin/staff'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/_authenticated/admin/dienstplan'
    | '/_authenticated/admin/import-zuordnungen'
    | '/_authenticated/admin/kasse'
    | '/_authenticated/admin/kasse-saldo'
    | '/_authenticated/admin/locations'
    | '/_authenticated/admin/migration'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/zeit'
    | '/_authenticated/admin/zeit-uebersicht'
    | '/_authenticated/zeit/abrechnung'
    | '/_authenticated/admin/'
    | '/_authenticated/zeit/'
    | '/_authenticated/admin/staff/$staffId'
    | '/_authenticated/admin/staff/new'
    | '/_authenticated/admin/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zeit/': {
      id: '/_authenticated/zeit/'
      path: '/zeit'
      fullPath: '/zeit/'
      preLoaderRoute: typeof AuthenticatedZeitIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/zeit/abrechnung': {
      id: '/_authenticated/zeit/abrechnung'
      path: '/zeit/abrechnung'
      fullPath: '/zeit/abrechnung'
      preLoaderRoute: typeof AuthenticatedZeitAbrechnungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/zeit-uebersicht': {
      id: '/_authenticated/admin/zeit-uebersicht'
      path: '/zeit-uebersicht'
      fullPath: '/admin/zeit-uebersicht'
      preLoaderRoute: typeof AuthenticatedAdminZeitUebersichtRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/zeit': {
      id: '/_authenticated/admin/zeit'
      path: '/zeit'
      fullPath: '/admin/zeit'
      preLoaderRoute: typeof AuthenticatedAdminZeitRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/migration': {
      id: '/_authenticated/admin/migration'
      path: '/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AuthenticatedAdminMigrationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/locations': {
      id: '/_authenticated/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AuthenticatedAdminLocationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kasse-saldo': {
      id: '/_authenticated/admin/kasse-saldo'
      path: '/kasse-saldo'
      fullPath: '/admin/kasse-saldo'
      preLoaderRoute: typeof AuthenticatedAdminKasseSaldoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kasse': {
      id: '/_authenticated/admin/kasse'
      path: '/kasse'
      fullPath: '/admin/kasse'
      preLoaderRoute: typeof AuthenticatedAdminKasseRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/import-zuordnungen': {
      id: '/_authenticated/admin/import-zuordnungen'
      path: '/import-zuordnungen'
      fullPath: '/admin/import-zuordnungen'
      preLoaderRoute: typeof AuthenticatedAdminImportZuordnungenRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dienstplan': {
      id: '/_authenticated/admin/dienstplan'
      path: '/dienstplan'
      fullPath: '/admin/dienstplan'
      preLoaderRoute: typeof AuthenticatedAdminDienstplanRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staff/': {
      id: '/_authenticated/admin/staff/'
      path: '/'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AuthenticatedAdminStaffIndexRouteImport
      parentRoute: typeof AuthenticatedAdminStaffRoute
    }
    '/_authenticated/admin/staff/new': {
      id: '/_authenticated/admin/staff/new'
      path: '/new'
      fullPath: '/admin/staff/new'
      preLoaderRoute: typeof AuthenticatedAdminStaffNewRouteImport
      parentRoute: typeof AuthenticatedAdminStaffRoute
    }
    '/_authenticated/admin/staff/$staffId': {
      id: '/_authenticated/admin/staff/$staffId'
      path: '/$staffId'
      fullPath: '/admin/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedAdminStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedAdminStaffRoute
    }
  }
}

interface AuthenticatedAdminStaffRouteChildren {
  AuthenticatedAdminStaffStaffIdRoute: typeof AuthenticatedAdminStaffStaffIdRoute
  AuthenticatedAdminStaffNewRoute: typeof AuthenticatedAdminStaffNewRoute
  AuthenticatedAdminStaffIndexRoute: typeof AuthenticatedAdminStaffIndexRoute
}

const AuthenticatedAdminStaffRouteChildren: AuthenticatedAdminStaffRouteChildren =
  {
    AuthenticatedAdminStaffStaffIdRoute: AuthenticatedAdminStaffStaffIdRoute,
    AuthenticatedAdminStaffNewRoute: AuthenticatedAdminStaffNewRoute,
    AuthenticatedAdminStaffIndexRoute: AuthenticatedAdminStaffIndexRoute,
  }

const AuthenticatedAdminStaffRouteWithChildren =
  AuthenticatedAdminStaffRoute._addFileChildren(
    AuthenticatedAdminStaffRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminDienstplanRoute: typeof AuthenticatedAdminDienstplanRoute
  AuthenticatedAdminImportZuordnungenRoute: typeof AuthenticatedAdminImportZuordnungenRoute
  AuthenticatedAdminKasseRoute: typeof AuthenticatedAdminKasseRoute
  AuthenticatedAdminKasseSaldoRoute: typeof AuthenticatedAdminKasseSaldoRoute
  AuthenticatedAdminLocationsRoute: typeof AuthenticatedAdminLocationsRoute
  AuthenticatedAdminMigrationRoute: typeof AuthenticatedAdminMigrationRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRouteWithChildren
  AuthenticatedAdminZeitRoute: typeof AuthenticatedAdminZeitRoute
  AuthenticatedAdminZeitUebersichtRoute: typeof AuthenticatedAdminZeitUebersichtRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminDienstplanRoute: AuthenticatedAdminDienstplanRoute,
    AuthenticatedAdminImportZuordnungenRoute:
      AuthenticatedAdminImportZuordnungenRoute,
    AuthenticatedAdminKasseRoute: AuthenticatedAdminKasseRoute,
    AuthenticatedAdminKasseSaldoRoute: AuthenticatedAdminKasseSaldoRoute,
    AuthenticatedAdminLocationsRoute: AuthenticatedAdminLocationsRoute,
    AuthenticatedAdminMigrationRoute: AuthenticatedAdminMigrationRoute,
    AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRouteWithChildren,
    AuthenticatedAdminZeitRoute: AuthenticatedAdminZeitRoute,
    AuthenticatedAdminZeitUebersichtRoute:
      AuthenticatedAdminZeitUebersichtRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedZeitAbrechnungRoute: typeof AuthenticatedZeitAbrechnungRoute
  AuthenticatedZeitIndexRoute: typeof AuthenticatedZeitIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedZeitAbrechnungRoute: AuthenticatedZeitAbrechnungRoute,
  AuthenticatedZeitIndexRoute: AuthenticatedZeitIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
