// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    let { data } = await supabase.auth.getSession();
    const nowSec = Math.floor(Date.now() / 1000);
    const expiresAt = data.session?.expires_at ?? 0;
    // Token fehlt ODER läuft in <30 s ab → einmal proaktiv refreshen.
    // Sonst landen abgelaufene Tokens am Server und kippen geschützte
    // beforeLoad-Calls (Admin-Gate) in den Root-Error-Boundary.
    if (!data.session?.access_token || expiresAt - nowSec < 30) {
      await supabase.auth.refreshSession();
      ({ data } = await supabase.auth.getSession());
    }
    const token = data.session?.access_token;
    if (!token) {
      // Öffentliche Server-Functions wie PIN-Login laufen VOR einer Session →
      // ohne Token weiterreichen. Geschützte Functions lehnt requireSupabaseAuth
      // serverseitig ab; in dem Fall ist die Session abgelaufen/geleert worden,
      // ohne dass das _authenticated-Gate neu greifen konnte (z. B. weil der Tab
      // offen blieb). Wir leiten dann hart auf /auth und BRECHEN den RPC ab,
      // damit der Aufruf nicht ohne Header rausgeht und als unverständlicher
      // 401 („No authorization header provided") den Error-Boundary blankt.
      // Ausnahme: bewusst öffentliche Routen (Display-Anzeige, öffentliche
      // API-Endpunkte, Passwort-Reset, Auth selbst) dürfen ohne Session
      // laufen — z. B. ruft die Root-Komponente beim ersten Rendern die
      // öffentliche `getSentryClientConfig`-Function auf. Ohne diese
      // Ausnahme würden die Kitchen-Displays (/display/$id) sofort auf
      // /auth umgeleitet, sobald irgendein serverFn ohne Session feuert.
      const path =
        typeof window !== "undefined" ? window.location.pathname : "";
      const isPublicPath =
        path.startsWith("/auth") ||
        path.startsWith("/display/") ||
        path.startsWith("/api/public/") ||
        path.startsWith("/reset-password");
      if (typeof window !== "undefined" && !isPublicPath) {
        window.location.replace("/auth");
        // Promise, die nie auflöst — der Redirect entlädt die Seite ohnehin.
        await new Promise<never>(() => {});
      }
      return next();
    }
    return next({
      headers: { Authorization: `Bearer ${token}` },
    });
  },
);
