// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    let { data } = await supabase.auth.getSession();
    if (!data.session?.access_token) {
      // Access-Token fehlt/abgelaufen → mit Refresh-Token einmal erneuern.
      await supabase.auth.refreshSession();
      ({ data } = await supabase.auth.getSession());
    }
    const token = data.session?.access_token;
    if (!token) {
      // Keine gültige Sitzung mehr → zurück zum Login, statt einen
      // unauthentifizierten RPC zu senden (würde im Server-Middleware 401en
      // und die Seite ohne Redirect blank lassen).
      if (typeof window !== "undefined") {
        window.location.assign("/auth");
      }
      throw new Error("Sitzung abgelaufen – bitte erneut anmelden.");
    }
    return next({
      headers: { Authorization: `Bearer ${token}` },
    });
  },
);
