// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyvblrdhutztbkoynnrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5dmJscmRodXR6dGJrb3lubnJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEyNzg4MjQsImV4cCI6MjA5Njg1NDgyNH0.JI3GJWhSMmvEdk75IZb5QVAmAYAzsQ8Pez1TO1x5ChI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});